name: CI

on:
  push:
    branches: [ navy ]
  pull_request:
    branches: [ navy ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  NVIMRS_LOG_FILE: nvim-rs.log
  NVIMRS_LOG_LEVEL: debug
  NVIMRS_STDERR: nvim-rs.stderr
  RUSTFLAGS: -C opt-level=0

jobs:
  all:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --all-targets
      - run: cargo fmt --check --all
      - run: cargo clippy --all-targets
      - run: cargo build --example basic
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
        id: neovim
      - run: cargo test -- --nocapture
        env:
          NVIMRS_TEST_BIN: ${{ steps.neovim.outputs.executable }}
